const { runListedNodeTests } = require("../../scripts/nodeTestRunner");

const testFiles = [
    "exportReplayUtils.test.js",
    "exportReplayWorker.test.js",
    "functions.test.js",
    "storage.test.js",
    "localPathOpener.test.js",
    "toastContainer.test.js",
    "models.test.js",
    "exportErrors.test.js",
    "exportDurationOptions.test.js",
    "exportReplayService.test.js",
    "exportReplayFlow.test.js",
    "exportReplayConfirmAction.test.js",
    "exportSaveDialog.test.js",
    "exportStartActions.test.js",
    "exportAvailability.test.js",
    "exportVideoActions.test.js",
    "exportErrorDetailsActions.test.js",
    "exportNotifications.test.js",
    "exportSettingsActions.test.js",
    "exportDialogOptions.test.js",
    "exportOptionActions.test.js",
    "timeFormatting.test.js",
    "polling.test.js",
    "externalLinks.test.js",
    "dashboardValues.test.js",
    "documentPaths.test.js",
    "documentFolderActions.test.js",
    "settingsFolderActions.test.js",
    "settingsLanguageActions.test.js",
    "settingsConfigActions.test.js",
    "settingsOptions.test.js",
    "recordToggle.test.js",
    "noBlockingAlerts.test.js",
];

runListedNodeTests({
    testDir: __dirname,
    testFiles,
});
